### PR TITLE
Heroku configuration

### PR DESCRIPTION
**Pull request by balfoldi**

### CODE REVIEW

**Comment by balfoldi** [comment]
Caution, import in root scss missing!!
heroku review app implemented, need experimentation starting with this pull request.

**Comment by balfoldi** [comment]
see https://dashboard.heroku.com/pipelines/71c35076-442b-44c7-a7ea-a2c5a88fbdaa
Ask me if you need access

**Comment by balfoldi** [comment]
Select all commits but "validates translated" to views actual changs

**Review by RigateStudio — APPROVED** [review]
ras

**Pull request merged**
